//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FutbotModel", "FK_CardItems_CardTypes", "CardType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Futbot.Models.CardType), "CardItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Futbot.Models.CardItem), true)]
[assembly: EdmRelationshipAttribute("FutbotModel", "FK_Cards_ChemistryMods", "CardItem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Futbot.Models.CardItem), "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Futbot.Models.Card), true)]
[assembly: EdmRelationshipAttribute("FutbotModel", "FK_Cards_Positions", "CardItem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Futbot.Models.CardItem), "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Futbot.Models.Card), true)]
[assembly: EdmRelationshipAttribute("FutbotModel", "FK_ScriptQueues_Accounts", "Account", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Futbot.Models.Account), "ScriptQueue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Futbot.Models.ScriptQueue), true)]

#endregion

namespace Futbot.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FutbotEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FutbotEntities object using the connection string found in the 'FutbotEntities' section of the application configuration file.
        /// </summary>
        public FutbotEntities() : base("name=FutbotEntities", "FutbotEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FutbotEntities object.
        /// </summary>
        public FutbotEntities(string connectionString) : base(connectionString, "FutbotEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FutbotEntities object.
        /// </summary>
        public FutbotEntities(EntityConnection connection) : base(connection, "FutbotEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardItem> CardItems
        {
            get
            {
                if ((_CardItems == null))
                {
                    _CardItems = base.CreateObjectSet<CardItem>("CardItems");
                }
                return _CardItems;
            }
        }
        private ObjectSet<CardItem> _CardItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Card> Cards
        {
            get
            {
                if ((_Cards == null))
                {
                    _Cards = base.CreateObjectSet<Card>("Cards");
                }
                return _Cards;
            }
        }
        private ObjectSet<Card> _Cards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardType> CardTypes
        {
            get
            {
                if ((_CardTypes == null))
                {
                    _CardTypes = base.CreateObjectSet<CardType>("CardTypes");
                }
                return _CardTypes;
            }
        }
        private ObjectSet<CardType> _CardTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScriptQueue> ScriptQueues
        {
            get
            {
                if ((_ScriptQueues == null))
                {
                    _ScriptQueues = base.CreateObjectSet<ScriptQueue>("ScriptQueues");
                }
                return _ScriptQueues;
            }
        }
        private ObjectSet<ScriptQueue> _ScriptQueues;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardItems(CardItem cardItem)
        {
            base.AddObject("CardItems", cardItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCards(Card card)
        {
            base.AddObject("Cards", card);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardTypes(CardType cardType)
        {
            base.AddObject("CardTypes", cardType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScriptQueues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScriptQueues(ScriptQueue scriptQueue)
        {
            base.AddObject("ScriptQueues", scriptQueue);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FutbotModel", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="accountId">Initial value of the AccountId property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="securityQuestion">Initial value of the SecurityQuestion property.</param>
        public static Account CreateAccount(global::System.Int32 accountId, global::System.String email, global::System.String password, global::System.String securityQuestion)
        {
            Account account = new Account();
            account.AccountId = accountId;
            account.Email = email;
            account.Password = password;
            account.SecurityQuestion = securityQuestion;
            return account;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                if (_AccountId != value)
                {
                    OnAccountIdChanging(value);
                    ReportPropertyChanging("AccountId");
                    _AccountId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccountId");
                    OnAccountIdChanged();
                }
            }
        }
        private global::System.Int32 _AccountId;
        partial void OnAccountIdChanging(global::System.Int32 value);
        partial void OnAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecurityQuestion
        {
            get
            {
                return _SecurityQuestion;
            }
            set
            {
                OnSecurityQuestionChanging(value);
                ReportPropertyChanging("SecurityQuestion");
                _SecurityQuestion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecurityQuestion");
                OnSecurityQuestionChanged();
            }
        }
        private global::System.String _SecurityQuestion;
        partial void OnSecurityQuestionChanging(global::System.String value);
        partial void OnSecurityQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Coin
        {
            get
            {
                return _Coin;
            }
            set
            {
                OnCoinChanging(value);
                ReportPropertyChanging("Coin");
                _Coin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Coin");
                OnCoinChanged();
            }
        }
        private Nullable<global::System.Int32> _Coin;
        partial void OnCoinChanging(Nullable<global::System.Int32> value);
        partial void OnCoinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ConnectionStatus
        {
            get
            {
                return _ConnectionStatus;
            }
            set
            {
                OnConnectionStatusChanging(value);
                ReportPropertyChanging("ConnectionStatus");
                _ConnectionStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectionStatus");
                OnConnectionStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _ConnectionStatus;
        partial void OnConnectionStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnConnectionStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SearchStatus
        {
            get
            {
                return _SearchStatus;
            }
            set
            {
                OnSearchStatusChanging(value);
                ReportPropertyChanging("SearchStatus");
                _SearchStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SearchStatus");
                OnSearchStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _SearchStatus;
        partial void OnSearchStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnSearchStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_ScriptQueues_Accounts", "ScriptQueue")]
        public EntityCollection<ScriptQueue> ScriptQueues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ScriptQueue>("FutbotModel.FK_ScriptQueues_Accounts", "ScriptQueue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ScriptQueue>("FutbotModel.FK_ScriptQueues_Accounts", "ScriptQueue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FutbotModel", Name="Card")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Card : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Card object.
        /// </summary>
        /// <param name="cardId">Initial value of the CardId property.</param>
        /// <param name="cardTypeId">Initial value of the CardTypeId property.</param>
        public static Card CreateCard(global::System.Int32 cardId, global::System.Int32 cardTypeId)
        {
            Card card = new Card();
            card.CardId = cardId;
            card.CardTypeId = cardTypeId;
            return card;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardId
        {
            get
            {
                return _CardId;
            }
            set
            {
                if (_CardId != value)
                {
                    OnCardIdChanging(value);
                    ReportPropertyChanging("CardId");
                    _CardId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardId");
                    OnCardIdChanged();
                }
            }
        }
        private global::System.Int32 _CardId;
        partial void OnCardIdChanging(global::System.Int32 value);
        partial void OnCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardTypeId
        {
            get
            {
                return _CardTypeId;
            }
            set
            {
                OnCardTypeIdChanging(value);
                ReportPropertyChanging("CardTypeId");
                _CardTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardTypeId");
                OnCardTypeIdChanged();
            }
        }
        private global::System.Int32 _CardTypeId;
        partial void OnCardTypeIdChanging(global::System.Int32 value);
        partial void OnCardTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChemistryModId
        {
            get
            {
                return _ChemistryModId;
            }
            set
            {
                OnChemistryModIdChanging(value);
                ReportPropertyChanging("ChemistryModId");
                _ChemistryModId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChemistryModId");
                OnChemistryModIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ChemistryModId;
        partial void OnChemistryModIdChanging(Nullable<global::System.Int32> value);
        partial void OnChemistryModIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PositionId
        {
            get
            {
                return _PositionId;
            }
            set
            {
                OnPositionIdChanging(value);
                ReportPropertyChanging("PositionId");
                _PositionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PositionId");
                OnPositionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PositionId;
        partial void OnPositionIdChanging(Nullable<global::System.Int32> value);
        partial void OnPositionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuyPrice
        {
            get
            {
                return _BuyPrice;
            }
            set
            {
                OnBuyPriceChanging(value);
                ReportPropertyChanging("BuyPrice");
                _BuyPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuyPrice");
                OnBuyPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _BuyPrice;
        partial void OnBuyPriceChanging(Nullable<global::System.Int32> value);
        partial void OnBuyPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SellPrice
        {
            get
            {
                return _SellPrice;
            }
            set
            {
                OnSellPriceChanging(value);
                ReportPropertyChanging("SellPrice");
                _SellPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellPrice");
                OnSellPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _SellPrice;
        partial void OnSellPriceChanging(Nullable<global::System.Int32> value);
        partial void OnSellPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPrice
        {
            get
            {
                return _MaxPrice;
            }
            set
            {
                OnMaxPriceChanging(value);
                ReportPropertyChanging("MaxPrice");
                _MaxPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPrice");
                OnMaxPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPrice;
        partial void OnMaxPriceChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuyPercent
        {
            get
            {
                return _BuyPercent;
            }
            set
            {
                OnBuyPercentChanging(value);
                ReportPropertyChanging("BuyPercent");
                _BuyPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuyPercent");
                OnBuyPercentChanged();
            }
        }
        private Nullable<global::System.Int32> _BuyPercent;
        partial void OnBuyPercentChanging(Nullable<global::System.Int32> value);
        partial void OnBuyPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SellPercent
        {
            get
            {
                return _SellPercent;
            }
            set
            {
                OnSellPercentChanging(value);
                ReportPropertyChanging("SellPercent");
                _SellPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellPercent");
                OnSellPercentChanged();
            }
        }
        private Nullable<global::System.Int32> _SellPercent;
        partial void OnSellPercentChanging(Nullable<global::System.Int32> value);
        partial void OnSellPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AverageValue
        {
            get
            {
                return _AverageValue;
            }
            set
            {
                OnAverageValueChanging(value);
                ReportPropertyChanging("AverageValue");
                _AverageValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AverageValue");
                OnAverageValueChanged();
            }
        }
        private Nullable<global::System.Int32> _AverageValue;
        partial void OnAverageValueChanging(Nullable<global::System.Int32> value);
        partial void OnAverageValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SearchStatus
        {
            get
            {
                return _SearchStatus;
            }
            set
            {
                OnSearchStatusChanging(value);
                ReportPropertyChanging("SearchStatus");
                _SearchStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SearchStatus");
                OnSearchStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _SearchStatus;
        partial void OnSearchStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnSearchStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> UpdateStatus
        {
            get
            {
                return _UpdateStatus;
            }
            set
            {
                OnUpdateStatusChanging(value);
                ReportPropertyChanging("UpdateStatus");
                _UpdateStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateStatus");
                OnUpdateStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _UpdateStatus;
        partial void OnUpdateStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnUpdateStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ExcessivePercent
        {
            get
            {
                return _ExcessivePercent;
            }
            set
            {
                OnExcessivePercentChanging(value);
                ReportPropertyChanging("ExcessivePercent");
                _ExcessivePercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExcessivePercent");
                OnExcessivePercentChanged();
            }
        }
        private Nullable<global::System.Int32> _ExcessivePercent;
        partial void OnExcessivePercentChanging(Nullable<global::System.Int32> value);
        partial void OnExcessivePercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPriceModifierPercent
        {
            get
            {
                return _MaxPriceModifierPercent;
            }
            set
            {
                OnMaxPriceModifierPercentChanging(value);
                ReportPropertyChanging("MaxPriceModifierPercent");
                _MaxPriceModifierPercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPriceModifierPercent");
                OnMaxPriceModifierPercentChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPriceModifierPercent;
        partial void OnMaxPriceModifierPercentChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPriceModifierPercentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_Cards_ChemistryMods", "CardItem")]
        public CardItem ChemistryMod
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardItem>("FutbotModel.FK_Cards_ChemistryMods", "CardItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardItem>("FutbotModel.FK_Cards_ChemistryMods", "CardItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CardItem> ChemistryModReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardItem>("FutbotModel.FK_Cards_ChemistryMods", "CardItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CardItem>("FutbotModel.FK_Cards_ChemistryMods", "CardItem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_Cards_Positions", "CardItem")]
        public CardItem Position
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardItem>("FutbotModel.FK_Cards_Positions", "CardItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardItem>("FutbotModel.FK_Cards_Positions", "CardItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CardItem> PositionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardItem>("FutbotModel.FK_Cards_Positions", "CardItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CardItem>("FutbotModel.FK_Cards_Positions", "CardItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FutbotModel", Name="CardItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardItem object.
        /// </summary>
        /// <param name="cardItemId">Initial value of the CardItemId property.</param>
        /// <param name="cardTypeId">Initial value of the CardTypeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static CardItem CreateCardItem(global::System.Int32 cardItemId, global::System.Int32 cardTypeId, global::System.String name)
        {
            CardItem cardItem = new CardItem();
            cardItem.CardItemId = cardItemId;
            cardItem.CardTypeId = cardTypeId;
            cardItem.Name = name;
            return cardItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardItemId
        {
            get
            {
                return _CardItemId;
            }
            set
            {
                if (_CardItemId != value)
                {
                    OnCardItemIdChanging(value);
                    ReportPropertyChanging("CardItemId");
                    _CardItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardItemId");
                    OnCardItemIdChanged();
                }
            }
        }
        private global::System.Int32 _CardItemId;
        partial void OnCardItemIdChanging(global::System.Int32 value);
        partial void OnCardItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardTypeId
        {
            get
            {
                return _CardTypeId;
            }
            set
            {
                OnCardTypeIdChanging(value);
                ReportPropertyChanging("CardTypeId");
                _CardTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardTypeId");
                OnCardTypeIdChanged();
            }
        }
        private global::System.Int32 _CardTypeId;
        partial void OnCardTypeIdChanging(global::System.Int32 value);
        partial void OnCardTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_CardItems_CardTypes", "CardType")]
        public CardType CardType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardType>("FutbotModel.FK_CardItems_CardTypes", "CardType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardType>("FutbotModel.FK_CardItems_CardTypes", "CardType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CardType> CardTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardType>("FutbotModel.FK_CardItems_CardTypes", "CardType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CardType>("FutbotModel.FK_CardItems_CardTypes", "CardType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_Cards_ChemistryMods", "Card")]
        public EntityCollection<Card> Cards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Card>("FutbotModel.FK_Cards_ChemistryMods", "Card");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Card>("FutbotModel.FK_Cards_ChemistryMods", "Card", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_Cards_Positions", "Card")]
        public EntityCollection<Card> Cards1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Card>("FutbotModel.FK_Cards_Positions", "Card");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Card>("FutbotModel.FK_Cards_Positions", "Card", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FutbotModel", Name="CardType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardType object.
        /// </summary>
        /// <param name="cardTypeId">Initial value of the CardTypeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static CardType CreateCardType(global::System.Int32 cardTypeId, global::System.String name)
        {
            CardType cardType = new CardType();
            cardType.CardTypeId = cardTypeId;
            cardType.Name = name;
            return cardType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardTypeId
        {
            get
            {
                return _CardTypeId;
            }
            set
            {
                if (_CardTypeId != value)
                {
                    OnCardTypeIdChanging(value);
                    ReportPropertyChanging("CardTypeId");
                    _CardTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardTypeId");
                    OnCardTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _CardTypeId;
        partial void OnCardTypeIdChanging(global::System.Int32 value);
        partial void OnCardTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_CardItems_CardTypes", "CardItem")]
        public EntityCollection<CardItem> CardItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CardItem>("FutbotModel.FK_CardItems_CardTypes", "CardItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CardItem>("FutbotModel.FK_CardItems_CardTypes", "CardItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FutbotModel", Name="ScriptQueue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScriptQueue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScriptQueue object.
        /// </summary>
        /// <param name="scriptQueueId">Initial value of the ScriptQueueId property.</param>
        /// <param name="accountId">Initial value of the AccountId property.</param>
        /// <param name="scriptName">Initial value of the ScriptName property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="requestTime">Initial value of the RequestTime property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static ScriptQueue CreateScriptQueue(global::System.Int32 scriptQueueId, global::System.Int32 accountId, global::System.String scriptName, global::System.Int32 priority, global::System.DateTime requestTime, global::System.Int32 status)
        {
            ScriptQueue scriptQueue = new ScriptQueue();
            scriptQueue.ScriptQueueId = scriptQueueId;
            scriptQueue.AccountId = accountId;
            scriptQueue.ScriptName = scriptName;
            scriptQueue.Priority = priority;
            scriptQueue.RequestTime = requestTime;
            scriptQueue.Status = status;
            return scriptQueue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScriptQueueId
        {
            get
            {
                return _ScriptQueueId;
            }
            set
            {
                if (_ScriptQueueId != value)
                {
                    OnScriptQueueIdChanging(value);
                    ReportPropertyChanging("ScriptQueueId");
                    _ScriptQueueId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScriptQueueId");
                    OnScriptQueueIdChanged();
                }
            }
        }
        private global::System.Int32 _ScriptQueueId;
        partial void OnScriptQueueIdChanging(global::System.Int32 value);
        partial void OnScriptQueueIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                OnAccountIdChanging(value);
                ReportPropertyChanging("AccountId");
                _AccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountId");
                OnAccountIdChanged();
            }
        }
        private global::System.Int32 _AccountId;
        partial void OnAccountIdChanging(global::System.Int32 value);
        partial void OnAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScriptName
        {
            get
            {
                return _ScriptName;
            }
            set
            {
                OnScriptNameChanging(value);
                ReportPropertyChanging("ScriptName");
                _ScriptName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScriptName");
                OnScriptNameChanged();
            }
        }
        private global::System.String _ScriptName;
        partial void OnScriptNameChanging(global::System.String value);
        partial void OnScriptNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.Int32 _Priority;
        partial void OnPriorityChanging(global::System.Int32 value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestTime
        {
            get
            {
                return _RequestTime;
            }
            set
            {
                OnRequestTimeChanging(value);
                ReportPropertyChanging("RequestTime");
                _RequestTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestTime");
                OnRequestTimeChanged();
            }
        }
        private global::System.DateTime _RequestTime;
        partial void OnRequestTimeChanging(global::System.DateTime value);
        partial void OnRequestTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgentId
        {
            get
            {
                return _AgentId;
            }
            set
            {
                OnAgentIdChanging(value);
                ReportPropertyChanging("AgentId");
                _AgentId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AgentId");
                OnAgentIdChanged();
            }
        }
        private global::System.String _AgentId;
        partial void OnAgentIdChanging(global::System.String value);
        partial void OnAgentIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FutbotModel", "FK_ScriptQueues_Accounts", "Account")]
        public Account Account
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("FutbotModel.FK_ScriptQueues_Accounts", "Account").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("FutbotModel.FK_ScriptQueues_Accounts", "Account").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Account> AccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Account>("FutbotModel.FK_ScriptQueues_Accounts", "Account");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Account>("FutbotModel.FK_ScriptQueues_Accounts", "Account", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
